
[functions.request-super-admin-key]
enabled = true
verify_jwt = false
entrypoint = "./functions/request-super-admin-key/index.ts"

[functions.verify-super-admin-key]
enabled = true
verify_jwt = false
entrypoint = "./functions/verify-super-admin-key/index.ts"
